image: node:12.18.3-stretch

stages:
  - installation
  - code quality
  - build application

npm:install:
  stage: installation
  dependencies: []
  cache:
    paths:
      - node_modules/
    policy: push
  interruptible: true
  script: npm ci

lint:codebase:
  stage: code quality
  dependencies: []
  cache:
    paths:
      - node_modules/
    policy: pull
  interruptible: true
  needs: ['npm:install']
  script: npm run lint

npm:build:
  stage: build application
  dependencies: []
  cache:
    paths:
      - node_modules/
    policy: pull
  interruptible: true
  needs: ['npm:install']
  script: npm run build
